version: "3"

services:
  database:
    image: library/postgres:14
    container_name: eventstoredb
    environment:
      POSTGRES_USER: 'marten'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'postgres'
    ports:
      - "5400:5432"
    volumes:
    - ./data:/var/lib/postgresql/data
